apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: app1
spec:
  destination:
    namespace: app1
    server: https://kubernetes.dev.svc
  project: project1
  source:
    path: components/app1/
    repoURL: https://github.com/jportasa/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true