apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vfarcic
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: production
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        image:
          tag: 2.9.17
