apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vfarcic
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/jportasa/devops-toolkit-series
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/pullsecret: argocd/ghcr-secret
spec:
  destination:
    namespace: production
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        image:
          tag: 2.9.16
          repository: ghcr.io/jportasa/devops-toolkit-series
  syncPolicy:
    automated:
      prune: true
      selfHeal: true