apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: dev
  name: app1
  namespace: app1
spec:
  destination:
    namespace: app1
    server: https://kubernetes.default.svc
  project: project1
  source:
    path: components/app1/
    repoURL: https://github.com/jportasa/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true